AddonId: NintendoLibrary
Packages:
  - Version: 1.15
    RequiredApiVersion: 6.12.0
    ReleaseDate: 2025-07-20
    PackageUrl: https://github.com/XenorPLxx/playnite-library-nintendo/releases/download/1.15/NintendoLibrary_1_15.pext
    Changelog:
      - Improves login experience
  - Version: 1.14
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2025-05-31
    PackageUrl: https://github.com/XenorPLxx/playnite-library-nintendo/releases/download/1.14/NintendoLibrary_1_14.pext
    Changelog:
      - Improves platform recognition (by Jeshibu)
  - Version: 1.13
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2025-05-31
    PackageUrl: https://github.com/XenorPLxx/playnite-library-nintendo/releases/download/1.13/NintendoLibrary_1_13.pext
    Changelog:
      - Sets Switch 2 platform to OUNCE
  - Version: 1.12
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2025-05-31
    PackageUrl: https://github.com/XenorPLxx/playnite-library-nintendo/releases/download/1.12/NintendoLibrary_1_12.pext
    Changelog:
      - Sets language to en-GB forced
  - Version: 1.11
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2025-05-31
    PackageUrl: https://github.com/XenorPLxx/playnite-library-nintendo/releases/download/1.11/NintendoLibrary_1_11.pext
    Changelog:
      - Improved debug messaging
  - Version: 1.10
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2025-05-31
    PackageUrl: https://github.com/XenorPLxx/playnite-library-nintendo/releases/download/1.10/NintendoLibrary_1_10.pext
    Changelog:
      - Switches to Virtual Game Cards page for game discovery
  - Version: 1.9
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2025-01-01
    PackageUrl: https://github.com/XenorPLxx/playnite-library-nintendo/releases/download/1.9/NintendoLibrary_1_9.pext
    Changelog:
      -  Fixes authentication (Jeshibu)
  - Version: 1.8
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-11-30
    PackageUrl: https://github.com/XenorPLxx/playnite-library-nintendo/releases/download/1.8/NintendoLibrary_1_8.pext
    Changelog:
      -  Improves cookie refresh
  - Version: 1.7
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-06-02
    PackageUrl: https://github.com/XenorPLxx/playnite-library-nintendo/releases/download/1.7/NintendoLibrary_1_7.pext
    Changelog:
      -  Fixes authentication redirects
  - Version: 1.6
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-02-05
    PackageUrl: https://github.com/XenorPLxx/playnite-library-nintendo/releases/download/1.6/NintendoLibrary_1_6.pext
    Changelog:
      -  Adds installation warning
  - Version: 1.5
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-11-03
    PackageUrl: https://github.com/XenorPLxx/playnite-library-nintendo/releases/download/1.5/NintendoLibrary_1_5.pext
    Changelog:
      - Updated the transactions URL
  - Version: 1.4
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-08-27
    PackageUrl: https://github.com/XenorPLxx/playnite-library-nintendo/releases/download/1.4/NintendoLibrary_1_4.pext
    Changelog:
      - Moved AOC content type to be included in downloaded games
  - Version: 1.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-13
    PackageUrl: https://github.com/XenorPLxx/playnite-library-nintendo/releases/download/1.3/NintendoLibrary_1_3.pext
    Changelog:
      - Added device code for WiiU
  - Version: 1.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-07
    PackageUrl: https://github.com/XenorPLxx/playnite-library-nintendo/releases/download/1.2/NintendoLibrary_1_2.pext
    Changelog:
      - Fixed cookie removal for reauthentication
  - Version: 1.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-07
    PackageUrl: https://github.com/XenorPLxx/playnite-library-nintendo/releases/download/1.1/NintendoLibrary_1_1.pext
    Changelog:
      - Added list filtration based on content type
  - Version: 1.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-06
    PackageUrl: https://github.com/XenorPLxx/playnite-library-nintendo/releases/download/1.0/NintendoLibrary_1_0.pext
    Changelog:
      - Playnite 9 support
      - Added Nintendo authentication
      - Added download of digital Nintendo purchases
